services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace_db
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
      
  node:
    image: "node:22-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./apps/api:/home/node/app
    depends_on:
      - db
    expose:
      - "8081"
      - "3000"
      - "5555"
    ports: # use if it is necessary to expose the container to the host machine
      - "8001:8001"
      - "3000:3000"
      - "5555:5555"
    entrypoint: sh -c 'rm -rf node_modules && npm ci && npx prisma db push && npx prisma generate && npm run seed-db && npx prisma studio && npm run start:dev'