name: CI Nexus

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  continuous-integration:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: | 
          cd apps/api 
          npm ci

      - name: Lint
        run: |
          cd apps/api 
          npm run lint

      - name: Generate prisma
        run: |
          cd apps/api 
          npx prisma generate

      - name: Build
        run: |
          cd apps/api 
          npm run build

      - name: Run Docker Database for tests
        run: | 
          docker compose up -d db
          sleep 10
          docker compose logs

      - name: Migrate Prisma
        run: |
          cd apps/api 
          npm run ci:migrate-prisma

      - name: Seed Prisma
        run: |
          cd apps/api 
          npm run ci:seed-db

      - name: Test
        run: |
          cd apps/api
          npm run test

      - name: Frontend Build
        run: |
          cd apps/web
          npm run build
      
