name: Deploy COOPERA

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: "Limpar diretório na VPS"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            rm -rf /marketplace/IC045-marketplace-ufba/*
      
      - name: "Copiar arquivos para a VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          source: "."
          target: "/marketplace/IC045-marketplace-ufba/"

      - name: "Renomear o ".env.ci" da api para ".env"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /marketplace/IC045-marketplace-ufba/apps/api/
            mv .env.ci .env

      - name: "Executar script de produção"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /marketplace/IC045-marketplace-ufba/prod
            ./update_env.sh

      - name: "Levantando o banco de dados"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /opt/docker/testes/
            docker-compose up -d

      - name: "Executar o pm2 para levantar o sistema"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            pm2 start coopera-front
            pm2 start coopera-back
            pm2 start coopera-prisma
